### PR TITLE
Use https instead

### LINKED ISSUE #3: request to use https instead of http
hi @mattn  I just test:
`echo webapi#http#get('http://suggestqueries.google.com/complete/search', {"client" : "youtube", "q" : "spacevim", "hjson" : "t", "hl" : g:googlesugges
t_language, "ie" : "UTF8", "oe" : "UTF8" })`

I see `{'status': '500', 'header': [], 'message': 'Couldn''t connect to host', 'content': ''}`, after changging to https, everything works well.

### PR DESCRIPTION
**Pull request by wsdjeg**
close #3

### CODE REVIEW

**Comment by mattn** [comment]
Thank you

**Comment by wsdjeg** [comment]
@mattn welcome, this is a nice plugin, and is there a suggest completion plugin for Wikipedia?

**Comment by mattn** [comment]
What the candidate for completion you expect?

**Comment by wsdjeg** [comment]
for example, on the topright of  this page, https://en.wikipedia.org/wiki/Vim, you will see a search box, if you insert vim, you will see a list of suggestion. each one will link you to another wiki.

**Comment by mattn** [comment]
Ah, may be good, but you shouldn't use wikipedia for that because wikipedia doesn't have good feeling for scraping.

**Comment by wsdjeg** [comment]
yeah, I hope Wikipedia could provide a api just like github's v3 api.

**Comment by mattn** [comment]
If you hope, you can use MediaWiki APIs.

**Comment by wsdjeg** [comment]
I am reading the api document of that site. will try to get that feature. thanks!

**Pull request merged**
